window.QIUZHAO = {
  checkedAt: "2026-09-01",
  cohort: "2027届",
  graduateWindow: "2026年9月 – 2027年8月",
  statuses: [
    "未投",
    "已投",
    "测评",
    "笔试",
    "一面",
    "二面",
    "三面",
    "HR",
    "意向",
    "Offer",
    "挂",
    "拒"
  ],
  companies: [
    {
      id: "bytedance",
      name: "字节跳动",
      tier: "大厂",
      industry: "互联网",
      batch: "全年",
      window: "2026-08-03 至 2026-12-31（本年 2 次投递）",
      deadline: "2026-12-31",
      roles: ["UX", "视觉", "动效", "品牌"],
      cities: ["北京", "上海", "深圳", "杭州"],
      test: "部分岗",
      written: "部分岗",
      interview: "3–4 轮 + HR",
      hiring: "open",
      url: "https://jobs.bytedance.com/campus",
      note: "校招全年开放。2026 年内 2 次投递，2027-01-01 再刷新 2 次。勾选「正式」。"
    },
    {
      id: "tencent",
      name: "腾讯",
      tier: "大厂",
      industry: "互联网",
      batch: "正式批",
      window: "2026-08-18 起，截止逐岗",
      deadline: "",
      roles: ["UX", "视觉", "动效", "游戏美术"],
      cities: ["深圳", "北京", "上海", "广州", "成都"],
      test: "常见",
      written: "常见",
      interview: "2–3 轮 + HR",
      hiring: "open",
      url: "https://careers.tencent.com/campus",
      note: "2027 全球校招正式批 8 月 18 日启动。设计/产品/技术同步开，截止看职位页。"
    },
    {
      id: "alibaba",
      name: "阿里巴巴",
      tier: "大厂",
      industry: "互联网",
      batch: "正式批",
      window: "2026-08-05 启动，网申参考至 2026-10-04",
      deadline: "2026-10-04",
      roles: ["UX", "视觉", "动效", "品牌"],
      cities: ["杭州", "北京", "上海", "深圳"],
      test: "有",
      written: "8 月中旬起",
      interview: "8 月中旬起，多轮",
      hiring: "open",
      url: "https://talent.alibaba.com",
      note: "含阿里星等专项。测评/笔试约 8 月中旬起，意向常见 9 月下旬起。"
    },
    {
      id: "ant",
      name: "蚂蚁集团",
      tier: "大厂",
      industry: "互联网",
      batch: "正式批",
      window: "正式批至 2026-10-30",
      deadline: "2026-10-30",
      roles: ["UX", "视觉", "品牌"],
      cities: ["杭州", "上海", "北京", "深圳", "成都"],
      test: "有",
      written: "研发/算法每周场次；设计以通知为准",
      interview: "进入面试后不可自行终止",
      hiring: "open",
      url: "https://talent.antgroup.com",
      note: "每次最多 2 个意向岗。同一职位已投部门本季不可重复投。"
    },
    {
      id: "meituan",
      name: "美团",
      tier: "大厂",
      industry: "互联网",
      batch: "正式批",
      window: "图文称 2026-08-17 启动",
      deadline: "",
      roles: ["UX", "视觉", "动效"],
      cities: ["北京", "上海", "深圳", "成都"],
      test: "常见",
      written: "常见",
      interview: "2–3 轮 + HR",
      hiring: "open",
      url: "https://zhaopin.meituan.com",
      note: "北斗计划等专项另入口。岗位届别以官网筛选项为准。"
    },
    {
      id: "kuaishou",
      name: "快手",
      tier: "大厂",
      industry: "互联网",
      batch: "正式批",
      window: "滚动，招满即止",
      deadline: "",
      roles: ["UX", "视觉", "动效"],
      cities: ["北京", "上海", "深圳"],
      test: "部分岗",
      written: "部分岗",
      interview: "2–3 轮",
      hiring: "rolling",
      url: "https://zhaopin.kuaishou.cn",
      note: "快 Star、商业化设计、内容生态设计以职位页为准。"
    },
    {
      id: "xhs",
      name: "小红书",
      tier: "大厂",
      industry: "互联网",
      batch: "正式批",
      window: "以官网职位为准",
      deadline: "",
      roles: ["UX", "视觉", "品牌", "动效"],
      cities: ["上海", "北京"],
      test: "部分岗",
      written: "少",
      interview: "作品集评审 + 2–3 轮",
      hiring: "unknown",
      url: "https://job.xiaohongshu.com/campus",
      note: "设计岗很看作品集和社区感。官网动态以登录后职位列表为准。"
    },
    {
      id: "baidu",
      name: "百度",
      tier: "大厂",
      industry: "互联网",
      batch: "全年",
      window: "2026-07-09 至 2027-06-30",
      deadline: "2027-06-30",
      roles: ["UX", "视觉"],
      cities: ["北京", "上海", "深圳", "杭州"],
      test: "部分岗",
      written: "7 月中–10 月中，每周集中场",
      interview: "滚动",
      hiring: "open",
      url: "https://talent.baidu.com/jobs",
      note: "校招岗位全年开。并非所有候选人都笔试。Offer 常见 11 月起。"
    },
    {
      id: "jd",
      name: "京东",
      tier: "大厂",
      industry: "互联网",
      batch: "正式批",
      window: "TET / 综合 / 技术同步，截止逐岗",
      deadline: "",
      roles: ["UX", "视觉"],
      cities: ["北京", "上海", "成都"],
      test: "常见",
      written: "常见",
      interview: "2–3 轮",
      hiring: "open",
      url: "https://campus.jd.com",
      note: "TET 管培与设计研发岗不是同一通道，投前看清项目名。"
    },
    {
      id: "pdd",
      name: "拼多多 / Temu",
      tier: "大厂",
      industry: "互联网",
      batch: "正式批",
      window: "云帆计划，毕业窗口 2026.9–2027.8",
      deadline: "",
      roles: ["UX", "视觉"],
      cities: ["上海"],
      test: "常见",
      written: "常见",
      interview: "节奏快，轮次多",
      hiring: "open",
      url: "https://careers.pddglobalhr.com/campus",
      note: "强度大、上海为主。设计岗相对研发少，看清业务线。"
    },
    {
      id: "netease",
      name: "网易（互联网）",
      tier: "大厂",
      industry: "互联网",
      batch: "正式批",
      window: "campus.163.com 应届通道",
      deadline: "",
      roles: ["UX", "视觉", "动效"],
      cities: ["杭州", "广州", "北京", "上海"],
      test: "部分岗",
      written: "部分岗",
      interview: "2–3 轮",
      hiring: "open",
      url: "https://campus.163.com",
      note: "互娱 / 雷火是另一套官网，别投错。"
    },
    {
      id: "netease-game",
      name: "网易互娱",
      tier: "大厂",
      industry: "游戏",
      batch: "正式批",
      window: "2026-07-21 起，越早越快锁定",
      deadline: "",
      roles: ["游戏美术", "UX", "视觉", "动效"],
      cities: ["广州", "上海", "杭州"],
      test: "有",
      written: "7 月下旬起多批次",
      interview: "7 月下旬起",
      hiring: "open",
      url: "https://game.campus.163.com",
      note: "策划 / 美术 / 用户体验 / 市场同步开。互娱与雷火分开投。"
    },
    {
      id: "leihuo",
      name: "网易雷火",
      tier: "大厂",
      industry: "游戏",
      batch: "正式批",
      window: "至 2026-10-30",
      deadline: "2026-10-30",
      roles: ["游戏美术", "UX", "视觉", "动效"],
      cities: ["杭州", "上海"],
      test: "有",
      written: "常见",
      interview: "作品集 + 多轮",
      hiring: "open",
      url: "https://leihuo.163.com/campus",
      note: "游戏研发、策划、美术、测试、产品运营。截止口径 10 月 30 日。"
    },
    {
      id: "bilibili",
      name: "哔哩哔哩",
      tier: "中厂",
      industry: "互联网",
      batch: "正式批",
      window: "B-UP 2027，截止逐岗",
      deadline: "",
      roles: ["UX", "视觉", "动效", "品牌"],
      cities: ["上海"],
      test: "部分岗",
      written: "少",
      interview: "作品集 + 2–3 轮",
      hiring: "open",
      url: "https://campus.bilibili.com",
      note: "上海为主。设计岗看作品集完整度和站内产品感觉。"
    },
    {
      id: "didi",
      name: "滴滴出行",
      tier: "大厂",
      industry: "互联网",
      batch: "正式批",
      window: "校园入口已开，截止逐岗",
      deadline: "",
      roles: ["UX", "视觉"],
      cities: ["北京", "杭州"],
      test: "部分岗",
      written: "部分岗",
      interview: "2–3 轮",
      hiring: "open",
      url: "https://campus.didiglobal.com",
      note: "提前批 / 储备实习与正式校招筛选项不同。"
    },
    {
      id: "dewu",
      name: "得物",
      tier: "中厂",
      industry: "互联网",
      batch: "正式批",
      window: "2026-08-17 启动，招满即止",
      deadline: "",
      roles: ["UX", "视觉", "品牌"],
      cities: ["上海"],
      test: "部分岗",
      written: "少",
      interview: "2–3 轮",
      hiring: "rolling",
      url: "https://www.dewu.com",
      note: "技术、产品、设计、运营、商业。投递入口以官方招聘页 / 公众号为准。"
    },
    {
      id: "weibo",
      name: "新浪微博",
      tier: "中厂",
      industry: "互联网",
      batch: "正式批",
      window: "2027 校招已开",
      deadline: "",
      roles: ["UX", "视觉", "品牌"],
      cities: ["北京"],
      test: "部分岗",
      written: "少",
      interview: "2 轮左右",
      hiring: "open",
      url: "https://career.sina.com.cn",
      note: "技术、产品、运营、内容、设计、职能都有。"
    },
    {
      id: "tme",
      name: "腾讯音乐",
      tier: "中厂",
      industry: "互联网",
      batch: "正式批",
      window: "招满即止",
      deadline: "",
      roles: ["UX", "视觉", "动效"],
      cities: ["深圳", "北京", "上海"],
      test: "部分岗",
      written: "少",
      interview: "2–3 轮",
      hiring: "rolling",
      url: "https://join.tencentmusic.com",
      note: "音乐产品设计密度高，作品集最好有播放器 / 内容分发案例。"
    },
    {
      id: "shopee",
      name: "Shopee 研发中心",
      tier: "中厂",
      industry: "互联网",
      batch: "正式批",
      window: "至 2026-09-30",
      deadline: "2026-09-30",
      roles: ["UX", "视觉"],
      cities: ["深圳", "上海"],
      test: "常见",
      written: "常见",
      interview: "英文沟通可能出现",
      hiring: "closing",
      url: "https://careers.shopee.cn",
      note: "截止口径 9 月 30 日，偏晚投要抓紧。主通道仍是研发，设计岗需职位页确认。"
    },
    {
      id: "deepseek",
      name: "DeepSeek",
      tier: "中厂",
      industry: "互联网",
      batch: "正式批",
      window: "Join DeepSeek 岗位页",
      deadline: "",
      roles: ["UX", "视觉"],
      cities: ["北京", "杭州"],
      test: "未知",
      written: "未知",
      interview: "以通知为准",
      hiring: "unknown",
      url: "https://app.mokahr.com",
      note: "官网跳 Moka。以算法/研发为主，设计岗少，投前先搜职位。"
    },
    {
      id: "iflytek",
      name: "科大讯飞",
      tier: "中厂",
      industry: "互联网",
      batch: "正式批",
      window: "2027 秋招已启动",
      deadline: "",
      roles: ["UX", "视觉"],
      cities: ["合肥", "北京", "上海", "深圳"],
      test: "常见",
      written: "常见",
      interview: "2–3 轮",
      hiring: "open",
      url: "https://iflytek.zhiye.com",
      note: "研究算法、AI 研发、产品、设计、教育、交付都有。"
    },
    {
      id: "ctrip",
      name: "携程",
      tier: "中厂",
      industry: "互联网",
      batch: "正式批",
      window: "约 2026-08-26 起，每人限投 1 次（以官网为准）",
      deadline: "",
      roles: ["UX", "视觉"],
      cities: ["上海"],
      test: "常见",
      written: "部分岗",
      interview: "2–3 轮",
      hiring: "open",
      url: "https://careers.ctrip.com/#/campus",
      note: "投递次数紧，先改一版旅游 / 交易链路作品再投。"
    },
    {
      id: "huawei",
      name: "华为",
      tier: "大厂",
      industry: "硬件",
      batch: "正式批",
      window: "滚动批次，截止看公告",
      deadline: "",
      roles: ["UX", "视觉", "工业设计", "动效"],
      cities: ["深圳", "上海", "北京", "杭州", "东莞"],
      test: "有",
      written: "机试 / 专业测评常见",
      interview: "业务面 + 综合",
      hiring: "open",
      url: "https://career.huawei.com",
      note: "终端 / 云 / 车 BU 设计条线不同。终端 UX 与工业设计是两条岗。"
    },
    {
      id: "xiaomi",
      name: "小米",
      tier: "大厂",
      industry: "硬件",
      batch: "正式批",
      window: "2027 全球校招已开",
      deadline: "",
      roles: ["UX", "视觉", "工业设计", "动效"],
      cities: ["北京", "上海", "深圳", "南京"],
      test: "常见",
      written: "部分岗",
      interview: "作品集 + 多轮",
      hiring: "open",
      url: "https://hr.xiaomi.com/campus",
      note: "覆盖软件、汽车、产品设计、新零售。设计岗看系统和硬件一体作品。"
    },
    {
      id: "honor",
      name: "荣耀",
      tier: "大厂",
      industry: "硬件",
      batch: "正式批",
      window: "2026-08-18 启动",
      deadline: "",
      roles: ["UX", "视觉", "工业设计"],
      cities: ["深圳", "北京", "上海"],
      test: "常见",
      written: "部分岗",
      interview: "2–3 轮",
      hiring: "open",
      url: "https://career.hihonor.com",
      note: "与腾讯同日启动正式批。研发、产品设计、营销都有。"
    },
    {
      id: "oppo",
      name: "OPPO",
      tier: "大厂",
      industry: "硬件",
      batch: "正式批",
      window: "大学校园通道",
      deadline: "",
      roles: ["UX", "视觉", "工业设计", "动效"],
      cities: ["深圳", "东莞", "上海"],
      test: "常见",
      written: "部分岗",
      interview: "作品集 + 2–3 轮",
      hiring: "open",
      url: "https://careers.oppo.com/university/oppo/campus/",
      note: "ColorOS / 影像 / 工业设计是三条常见设计岗。"
    },
    {
      id: "vivo",
      name: "vivo",
      tier: "大厂",
      industry: "硬件",
      batch: "正式批",
      window: "以 hr.vivo.com 为准",
      deadline: "",
      roles: ["UX", "视觉", "工业设计"],
      cities: ["东莞", "深圳", "杭州"],
      test: "常见",
      written: "部分岗",
      interview: "2–3 轮",
      hiring: "open",
      url: "https://hr.vivo.com",
      note: "OriginOS 与影像设计岗看系统作品和落地能力。"
    },
    {
      id: "dji",
      name: "大疆 DJI",
      tier: "大厂",
      industry: "硬件",
      batch: "正式批",
      window: "2027 拓疆者，招满即止",
      deadline: "",
      roles: ["UX", "工业设计", "视觉"],
      cities: ["深圳", "上海"],
      test: "常见",
      written: "部分岗",
      interview: "作品集要求高",
      hiring: "rolling",
      url: "https://careers.dji.com",
      note: "机器人、飞行器、影像。工业设计与软件 UX 分岗。"
    },
    {
      id: "byd",
      name: "比亚迪",
      tier: "大厂",
      industry: "汽车",
      batch: "正式批",
      window: "网申已开，2026-09-01 后集中流程",
      deadline: "",
      roles: ["UX", "工业设计", "视觉"],
      cities: ["深圳", "西安", "上海"],
      test: "常见",
      written: "常见",
      interview: "多轮，场地可能在厂区",
      hiring: "open",
      url: "https://career.byd.com",
      note: "汽车智能化、座舱 HMI、造型。9 月起进入集中面试。"
    },
    {
      id: "nio",
      name: "蔚来",
      tier: "中厂",
      industry: "汽车",
      batch: "正式批",
      window: "Careers 校招生通道",
      deadline: "",
      roles: ["UX", "视觉", "动效"],
      cities: ["上海", "合肥", "北京"],
      test: "部分岗",
      written: "少",
      interview: "作品集 + 业务面",
      hiring: "open",
      url: "https://nio.cn/careers",
      note: "座舱、App、品牌设计分开招。"
    },
    {
      id: "xpeng",
      name: "小鹏",
      tier: "中厂",
      industry: "汽车",
      batch: "正式批",
      window: "探索者计划，校网曾标 8 月 31 日截止",
      deadline: "2026-08-31",
      roles: ["UX", "视觉", "动效"],
      cities: ["广州", "上海", "北京"],
      test: "部分岗",
      written: "少",
      interview: "2–3 轮",
      hiring: "closing",
      url: "https://xiaopeng.jobs.feishu.cn",
      note: "若系统仍开可补投。截止已过的岗位不要硬投。"
    },
    {
      id: "li",
      name: "理想汽车",
      tier: "中厂",
      industry: "汽车",
      batch: "正式批",
      window: "校园招聘列表",
      deadline: "",
      roles: ["UX", "视觉", "动效"],
      cities: ["北京", "上海", "常州"],
      test: "部分岗",
      written: "少",
      interview: "作品集 + 多轮",
      hiring: "unknown",
      url: "https://www.lixiang.com/employ/campus/list.html",
      note: "座舱与 App 设计看家庭场景和系统完整性。"
    },
    {
      id: "geely",
      name: "吉利控股",
      tier: "大厂",
      industry: "汽车",
      batch: "正式批",
      window: "分品牌开放",
      deadline: "",
      roles: ["UX", "工业设计", "视觉"],
      cities: ["杭州", "宁波", "上海"],
      test: "常见",
      written: "部分岗",
      interview: "2–3 轮",
      hiring: "open",
      url: "https://campus.geely.com",
      note: "极氪 / 领克 / 银河等品牌岗位不互通，看清雇主。"
    },
    {
      id: "mihoyo",
      name: "米哈游",
      tier: "大厂",
      industry: "游戏",
      batch: "正式批",
      window: "至 2026-10-30",
      deadline: "2026-10-30",
      roles: ["游戏美术", "UX", "视觉", "动效"],
      cities: ["上海"],
      test: "有",
      written: "技术岗有；美术看作品集",
      interview: "作品集是门槛",
      hiring: "open",
      url: "https://campus.mihoyo.com",
      note: "游戏研发、大模型、策划、美术。原画 / UI / 动效分得很细。"
    },
    {
      id: "paper",
      name: "叠纸游戏",
      tier: "中厂",
      industry: "游戏",
      batch: "正式批",
      window: "至 2026-10-30",
      deadline: "2026-10-30",
      roles: ["游戏美术", "UX", "视觉"],
      cities: ["上海"],
      test: "部分岗",
      written: "少",
      interview: "作品集 + 业务面",
      hiring: "open",
      url: "https://career.papegames.com",
      note: "偏女性向 / 换装。UI 与时装视觉是常见设计岗。"
    },
    {
      id: "lilith",
      name: "莉莉丝",
      tier: "中厂",
      industry: "游戏",
      batch: "提前批 / 正式批",
      window: "提前批已启动，正式批看职位页",
      deadline: "",
      roles: ["游戏美术", "UX", "视觉"],
      cities: ["上海"],
      test: "部分岗",
      written: "少",
      interview: "2–3 轮",
      hiring: "open",
      url: "https://lilithgames.jobs.feishu.cn",
      note: "2027 秋招提前批 7 月已见高校就业网。统一截止以官方职位为准。"
    },
    {
      id: "shengqu",
      name: "盛趣游戏",
      tier: "中厂",
      industry: "游戏",
      batch: "正式批",
      window: "至 2026-10-30",
      deadline: "2026-10-30",
      roles: ["游戏美术", "视觉"],
      cities: ["上海"],
      test: "部分岗",
      written: "少",
      interview: "2 轮左右",
      hiring: "open",
      url: "https://campus.shengqugames.com",
      note: "研发、策划、美术、发行运营、职能。"
    },
    {
      id: "cmb-network",
      name: "招银网络科技",
      tier: "中厂",
      industry: "金融",
      batch: "正式批",
      window: "至 2026-09-20",
      deadline: "2026-09-20",
      roles: ["UX"],
      cities: ["深圳", "杭州", "成都"],
      test: "有",
      written: "后端/前端/算法为主",
      interview: "2–3 轮",
      hiring: "closing",
      url: "https://career.cmbchina.com",
      note: "公告偏研发。体验设计岗如有，会写在招银网络科技职位里，截止 9 月 20 日。"
    },
    {
      id: "hzbank",
      name: "杭州银行",
      tier: "中厂",
      industry: "金融",
      batch: "正式批",
      window: "2026-08-21 发布，至 2026-10-22",
      deadline: "2026-10-22",
      roles: ["UX", "视觉"],
      cities: ["杭州"],
      test: "有",
      written: "行测 / 综合常见",
      interview: "笔试后面试",
      hiring: "open",
      url: "https://www.hzbank.com.cn",
      note: "培训生、金融市场、科技岗。设计岗少，科技体验岗需职位页确认。"
    },
    {
      id: "cmb",
      name: "招商银行",
      tier: "大厂",
      industry: "金融",
      batch: "正式批",
      window: "总行 / 分行分公告",
      deadline: "",
      roles: ["UX", "视觉"],
      cities: ["深圳", "上海", "杭州", "北京"],
      test: "有",
      written: "有",
      interview: "笔试 + 面试",
      hiring: "unknown",
      url: "https://career.cmbchina.com",
      note: "金融科技与零售体验偶发设计岗。以官方招聘站公告为准。"
    },
    {
      id: "icbc",
      name: "工商银行",
      tier: "大厂",
      industry: "金融",
      batch: "正式批",
      window: "总行金融科技 + 分行，看公告",
      deadline: "",
      roles: ["UX"],
      cities: ["北京", "上海", "广州", "深圳", "杭州"],
      test: "有",
      written: "统一笔试常见",
      interview: "笔试后面试",
      hiring: "unknown",
      url: "https://job.icbc.com.cn",
      note: "软开为主。体验岗极少，有则在金融科技条线。"
    },
    {
      id: "abchina",
      name: "农业银行",
      tier: "大厂",
      industry: "金融",
      batch: "正式批",
      window: "2027 届已更新",
      deadline: "",
      roles: ["UX"],
      cities: ["北京", "上海", "广州", "深圳"],
      test: "有",
      written: "有",
      interview: "笔试 + 面试",
      hiring: "open",
      url: "https://career.abchina.com.cn",
      note: "总行管培、金融科技、综合业务、分行。设计岗需在科技类里找。"
    },
    {
      id: "zte",
      name: "中兴通讯",
      tier: "大厂",
      industry: "硬件",
      batch: "提前批 / 正式批",
      window: "未来领军 6 月 29 日起",
      deadline: "",
      roles: ["UX", "视觉", "工业设计"],
      cities: ["深圳", "南京", "上海", "西安"],
      test: "有",
      written: "有",
      interview: "2–3 轮",
      hiring: "open",
      url: "https://job.zte.com.cn",
      note: "研发、营销、供应链、6G / AI / 芯片。UX 多在终端与网管。"
    },
    {
      id: "intel",
      name: "英特尔中国",
      tier: "外企",
      industry: "芯片",
      batch: "正式批",
      window: "学生 / 毕业生项目滚动",
      deadline: "",
      roles: ["UX", "视觉"],
      cities: ["上海", "北京", "成都"],
      test: "部分岗",
      written: "少",
      interview: "英文可能出现",
      hiring: "unknown",
      url: "https://jobs.intel.com",
      note: "设计岗少，偏软件体验与市场设计。投校招生项目。"
    },
    {
      id: "bosch",
      name: "博世中国",
      tier: "外企",
      industry: "汽车",
      batch: "正式批",
      window: "管培 / 研发校园项目",
      deadline: "",
      roles: ["UX", "工业设计"],
      cities: ["上海", "苏州", "无锡"],
      test: "部分岗",
      written: "少",
      interview: "中英都可能",
      hiring: "unknown",
      url: "https://www.bosch.com.cn/careers",
      note: "座舱 HMI、工业设计偶发。看 Early Careers / 校园。"
    },
    {
      id: "cxmt",
      name: "长鑫存储",
      tier: "中厂",
      industry: "芯片",
      batch: "正式批",
      window: "入口已核",
      deadline: "",
      roles: ["UX"],
      cities: ["合肥", "北京"],
      test: "常见",
      written: "常见",
      interview: "偏工程",
      hiring: "unknown",
      url: "https://cxmt.zhiye.com",
      note: "设计岗极少。列在这里是为了芯片方向扫一眼，不必强投。"
    },
    {
      id: "ymtc",
      name: "长江存储",
      tier: "中厂",
      industry: "芯片",
      batch: "提前批",
      window: "2027 届提前批入口已核",
      deadline: "",
      roles: ["UX"],
      cities: ["武汉"],
      test: "常见",
      written: "常见",
      interview: "偏工程",
      hiring: "unknown",
      url: "https://ymtc.zhiye.com",
      note: "同样工程为主。有体验岗再点开。"
    },
    {
      id: "sgcc",
      name: "国家电网",
      tier: "国企",
      industry: "国企",
      batch: "正式批",
      window: "以集团公告为准",
      deadline: "",
      roles: ["视觉"],
      cities: ["北京", "各省网"],
      test: "有",
      written: "统考 / 省考笔试",
      interview: "笔试后面试",
      hiring: "unknown",
      url: "https://zhaopin.sgcc.com.cn",
      note: "设计岗极少。宣传 / 数字媒体类看省侧公告。"
    },
    {
      id: "fanruan",
      name: "帆软",
      tier: "中厂",
      industry: "互联网",
      batch: "正式批",
      window: "面向 2026.9–2027.8 毕业生",
      deadline: "",
      roles: ["UX", "视觉"],
      cities: ["南京", "上海"],
      test: "部分岗",
      written: "少",
      interview: "2 轮左右",
      hiring: "open",
      url: "https://join.fanruan.com",
      note: "B 端报表产品，UX 看复杂信息设计。"
    }
  ]
};
